# Merkator nv/sa
# MarlinDT Network Intelligence (MNI) Build tag generate

trigger:
  paths:
    include:
    - '**'
    exclude:
    - src/mni.ini

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  persistCredentials: true
- script: |
    curl -L --output yq "https://github.com/mikefarah/yq/releases/download/v4.45.1/yq_linux_amd64" && \
    chmod 700 ./yq
  displayName: 'Install YQ'
  workingDirectory: $(System.DefaultWorkingDirectory)
- script: which sed &>/dev/null || sudo apt install -y sed
  displayName: 'Install SED'
  workingDirectory: $(System.DefaultWorkingDirectory)
- script: |
    git config --global user.email "pipeline@azure.com"
    git config --global user.name "Azure DevOps"
  displayName: 'Git Config'
  workingDirectory: $(System.DefaultWorkingDirectory)
- script: git checkout -b main
  displayName: 'Git Checkout'
  workingDirectory: $(System.DefaultWorkingDirectory)
- script: |
    MNI_VERSION=$(./yq -r ".info.version" api/mni.yaml)
    sed -i -e "s/MNI_VERSION=.*/MNI_VERSION=\"${MNI_VERSION}\"/" src/mni.ini && \
    sed -i -e "s/MNI_BUILD=.*/MNI_BUILD=\"$(Build.BuildNumber)\"/" src/mni.ini && \
    git diff --quiet src/mni.ini &>/dev/null || git add -f src/mni.ini
  displayName: 'Update build tag'
  workingDirectory: $(System.DefaultWorkingDirectory)
- script: |
    [[ -f "./yq" ]] && rm -f ./yq &>/dev/null
  displayName: 'Uninstall YQ'
  workingDirectory: $(System.DefaultWorkingDirectory)
- script: |
    git status
    git commit -m "pipeline@azure.com: Build tag generate $(Build.BuildNumber)"
    git pull --set-upstream origin main --rebase
    git push --set-upstream origin main 
  displayName: 'Git Commit/Push'
  workingDirectory: $(System.DefaultWorkingDirectory)
