# Merkator nv/sa
# MarlinDT Network Intelligence (MNI) CVE scan

trigger:
  paths:
    include:
    - 'src/apiServer/**'
    exclude:
    - api/mni.json
    - docs/mni.html

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  persistCredentials: true
- script: which jq &>/dev/null || sudo apt install -y jq &>/dev/null
  displayName: 'Install JQ'
  workingDirectory: $(System.DefaultWorkingDirectory)
- script: which node &>/dev/null || sudo apt install -y nodejs &>/dev/null
  displayName: 'Install NodeJS'
  workingDirectory: $(System.DefaultWorkingDirectory)
- script: |
    git config --global user.email "pipeline@azure.com"
    git config --global user.name "Azure DevOps"
    git config --global pull.rebase true
  displayName: 'Git Config'
  workingDirectory: $(System.DefaultWorkingDirectory)
- script: |
    git checkout -b main
  displayName: 'Git Checkout'
  workingDirectory: $(System.DefaultWorkingDirectory)
- script: |
    cd src/apiServer
    [[ -d "./node_modules" ]] && rm -R -f ./node_modules &>/dev/null
    [[ -f "./package-lock.json" ]] && rm -f ./package-lock.json &>/dev/null
    export NODE_NO_WARNINGS=1
    npm -y install --no-audit --no-fund --silent --omit=dev &>/dev/null 2>&1
  displayName: 'Install AuditJS OSSI'
  workingDirectory: $(System.DefaultWorkingDirectory)
- script: |
    cd src/apiServer
    export NODE_NO_WARNINGS=1
    npx -y --no-audit --no-fund --silent auditjs@latest ossi --whitelist ./cveignore.json --quiet --json &> ./cve.json 
    [[ $? -eq 0 ]] || cat ./cve.json|jq
    [[ -d "./node_modules" ]] && rm -R -f ./node_modules &>/dev/null
    [[ -f "./package-lock.json" ]] && rm -f ./package-lock.json &>/dev/null
    git pull --set-upstream origin main
    git diff --quiet ./cve.json &>/dev/null || git add -f ./cve.json
  displayName: 'CVE Scan'
  workingDirectory: $(System.DefaultWorkingDirectory)
- script: |
    git status
    git commit -m "pipeline@azure.com: CVE scan results $(Build.BuildNumber)"
    git pull --set-upstream origin main --rebase
    git push --set-upstream origin main 
  displayName: 'Git Commit/Push'
  workingDirectory: $(System.DefaultWorkingDirectory)
