erDiagram
    adminEmailSend {varchar id varchar adminEmailId varchar host integer port enum protocol enum authentication boolean encryptionEnabled boolean encryptionStartTls}
    costCable {enum technology enum unit decimal costPerUnit}
    secret {varchar scope varchar realm enum type timestamp expiration varchar identityProviderBase varchar identityProviderAuthorization varchar identityProviderToken varchar identityProviderWellKnown varchar plainUsername varchar plainPassword varchar sshUsername varchar sshKeyPassphrase varchar sshKeyPublic varchar sshKeyPrivate varchar sshHostCA varchar sslPrivate varchar sslCA enum snmpVersion varchar snmpCommunityRead varchar snmpCommunityWrite varchar snmpCommunityTrap varchar snmpUsername enum snmpAuthorizationProtocol varchar snmpAuthorizationPassword enum snmpEncryptionProtocol varchar snmpEncryptionPassword varchar tokenIdentity varchar tokenKey}
    _site {integer tsId timestamp point varchar siteId enum source decimal probability varchar reference timestamp commissioned timestamp decommissioned enum area enum type boolean onNet boolean hasDocument enum country varchar region varchar town varchar district varchar street varchar premisesNameNumber varchar postalCode decimal X decimal Y decimal Z varchar M varchar documentId point_3d geoPoint}
    _pole {integer tsId timestamp point varchar poleId enum source decimal probability varchar reference enum purpose decimal height enum classifier enum unit integer premisesPassed enum area boolean hasDocument varchar jobId varchar permitId timestamp plannedStart timestamp plannedCompletion integer plannedDuration enum plannedUnit timestamp actualStart timestamp actualCompletion integer actualDuration enum actualUnit enum state varchar connectsToSiteId varchar connectsToTrenchId varchar connectsToPoleId decimal X decimal Y decimal Z varchar M varchar documentId point_3d geoPoint}
    alertContent {varchar id timestamp point varchar alertId varchar content}
    _cableCoax {integer tsId timestamp point enum source varchar cableId decimal frequencyLow decimal frequencyHigh integer channels decimal width enum unit}
    _trenchCoordinate {integer tsId timestamp point integer trenchTsId varchar trenchId enum source decimal X decimal Y decimal Z varchar M point_3d geoPoint}
    adminMap {varchar id enum vendor boolean systemDefault varchar renderUrl enum typeSecret}
    alert {varchar id boolean delete varchar description varchar function}
    alertCallback {varchar id varchar alertId varchar requestorId varchar subscriptionId varchar callbackUrl enum authentication integer retries integer currentRetry integer retryDelay integer maxLifeRetries integer currentLifeRetries}
    cable {varchar id boolean delete timestamp tsPoint integer historicalTsId integer plannedTsId integer predictedTsId}
    trench {varchar id boolean delete timestamp tsPoint integer historicalTsId integer plannedTsId integer predictedTsId}
    _document {integer tsId enum source timestamp point decimal probability varchar documentId enum mimeType varchar path varchar name integer sizeBytes varchar md5Hash}
    alertWorkflow {varchar id varchar alertId varchar requestorId varchar workflowEngineId varchar workflowRunnerId varchar flowName}
    costPole {enum purpose enum classifier decimal costPerUnit}
    costService {enum type integer rate enum unit integer lagMembers decimal costPerUnit}
    _cableEthernet {integer tsId timestamp point enum source varchar cableId enum category integer rate enum unit}
    alertNotify {varchar id varchar alertId varchar requestorId varchar emailProviderId varchar notificationId varchar subject}
    alertPublish {varchar id varchar alertId varchar requestorId varchar publicationId varchar kafkaId varchar topic}
    costRack {integer slots decimal costPerUnit}
    predictQueue {integer qId timestamp point boolean delete enum resource varchar id enum state}
    rack {varchar id boolean delete timestamp tsPoint integer historicalTsId integer plannedTsId integer predictedTsId geometry geometry}
    _rackSlot {integer tsId timestamp point enum source decimal probability varchar rackId integer rackTsId integer slot enum usage varchar neId varchar host}
    adminEmailReceive {varchar id varchar adminEmailId varchar host integer port enum protocol boolean encryptionEnabled boolean encryptionStartTls varchar rootFolder enum folderSeparator}
    alertNotifyRecipient {varchar id varchar alertNotifyId varchar notificationId varchar recipient}
    alertQueue {integer qId timestamp point boolean delete enum alertType varchar alertId varchar callbackAlertId varchar publishAlertId varchar notifyAlertId varchar workflowAlertId}
    currency {varchar id varchar name enum symbol enum isoCode boolean systemDefault decimal rateFromDefault}
    site {varchar id boolean delete timestamp tsPoint integer historicalTsId integer plannedTsId integer predictedTsId}
    _ne {integer tsId timestamp point varchar neId enum source decimal probability varchar host varchar mgmtIP enum protocol integer port enum typeSecret varchar vendor varchar model varchar image varchar version timestamp commissioned timestamp decommissioned boolean hasDocument varchar siteId varchar rackId varchar slotPosition varchar config varchar documentId}
    _trench {integer tsId timestamp point varchar trenchId enum source decimal probability varchar reference enum purpose decimal depth enum classifier enum unit enum type integer premisesPassed enum area boolean hasDocument varchar jobId varchar permitId timestamp plannedStart timestamp plannedCompletion integer plannedDuration enum plannedUnit timestamp actualStart timestamp actualCompletion integer actualDuration enum actualUnit enum state varchar connectsToSiteId varchar connectsToTrenchId varchar connectsToPoleId varchar documentId}
    adminKafka {varchar id varchar name varchar clientId varchar host integer port integer retryDelay integer retries enum acks integer linger integer batchSize integer bufferMemory integer maxInFlightRequestsPerConnection enum compressionMethod enum authentication}
    cve {varchar id timestamp published timestamp updated varchar vendor varchar uri}
    _cableSingleFiber {integer tsId timestamp point enum source varchar cableId integer strands enum mode integer channels integer width enum unit}
    _nePortCoax {integer tsId integer neTsId decimal frequencyLow decimal frequencyHigh integer channels decimal width enum unit}
    _nePortXdsl {integer tsId integer neTsId enum category integer rate enum unit}
    adminEmail {varchar id varchar vendor varchar address varchar name}
    costDuct {enum category integer configuration enum unit decimal costPerUnit}
    _cableMultiFiber {integer tsId timestamp point enum source varchar cableId integer ribbons integer strands enum mode integer channels integer width enum unit}
    _rack {integer tsId timestamp point varchar rackId enum source decimal probability varchar reference timestamp commissioned timestamp decommissioned varchar siteId integer floor varchar floorArea integer floorRow integer floorColumn boolean hasDocument decimal X decimal Y decimal Z varchar M point_3d geoPoint decimal depth decimal height decimal width enum unit integer slots varchar documentId}
    costNe {varchar vendor varchar model decimal costPerUnit}
    cvePlatforms {integer id varchar cveId varchar platform}
    _duct {integer tsId timestamp point varchar ductId varchar trenchId enum source decimal probability enum purpose enum category boolean hasDocument integer configuration enum state varchar within decimal placementVertical decimal placementHorizontal enum placementUnit varchar documentId}
    cveVersions {integer id varchar cveId varchar lessThan varchar status varchar version varchar versionType}
    duct {varchar id boolean delete timestamp tsPoint integer historicalTsId integer plannedTsId integer predictedTsId}
    _cableCopper {integer tsId timestamp point enum source varchar cableId integer twistedPairs}
    _nePortFiber {integer tsId integer neTsId integer rate enum unit enum mode integer channels integer width}
    service {varchar id boolean delete timestamp tsPoint integer historicalTsId integer plannedTsId integer predictedTsId}
    _nePortEthernet {integer tsId integer neTsId enum category integer rate enum unit}
    _serviceIngress {integer tsId timestamp point enum source varchar serviceId integer serviceTsId varchar neId varchar nePort integer cVlanId integer sVlanId integer lagMember}
    adminWorkflow {varchar id varchar name varchar engineUrl enum engineType}
    costSite {enum area enum type decimal costPerUnit}
    fetchJob {varchar id boolean delete varchar description enum protocol varchar cronTime varchar neId varchar emailId varchar emailAddress varchar emailSubject varchar fileUrl varchar httpUrl varchar kafkaId varchar kafkaTopic varchar snmpReadOid blob snmpMib varchar workflowEngineId varchar workflowRunnerId varchar workflowName integer retries integer currentRetry integer retryDelay integer maxLifeRetries integer currentLifeRetries varchar function}
    document {varchar id boolean delete timestamp tsPoint integer historicalTsId integer plannedTsId integer predictedTsId}
    _cable {integer tsId timestamp point enum source decimal probability varchar cableId varchar reference varchar ductId varchar poleId enum technology boolean hasDocument enum state integer coaxTsId integer copperTsId integer ethernetTsId integer singleFiberTsId integer multiFiberTsId varchar documentId}
    _nePortLoopback {integer tsId integer neTsId integer rate enum unit}
    _serviceEgress {integer tsId timestamp point enum source varchar serviceId integer serviceTsId varchar neId varchar nePort integer cVlanId integer sVlanId integer lagMember}
    adminData {varchar id integer historicalDuration enum historicalUnit integer predictedDuration enum predictedUnit}
    fetchQueue {integer qId timestamp point boolean delete varchar fetchJobId}
    pole {varchar id boolean delete timestamp tsPoint integer historicalTsId integer plannedTsId integer predictedTsId}
    _nePort {integer tsId timestamp point enum source varchar neId integer neTsId varchar name enum technology enum state integer errorCount}
    _service {integer tsId timestamp point varchar serviceId enum source decimal probability varchar reference varchar customerName varchar customerReference timestamp commissioned timestamp decommissioned enum type boolean hasDocument integer rate enum unit varchar lagGroup integer lagMembers varchar documentId}
    costTrench {enum purpose enum type enum unit decimal costPerUnit}
    ne {varchar id boolean delete timestamp tsPoint integer historicalTsId integer plannedTsId integer predictedTsId}
    _nePortVirtual {integer tsId integer neTsId integer rate enum unit}
    alert }o--o{ alertPublish : "alertId"
    rack }o--o{ _rackSlot : "rackId"
    adminWorkflow }o--o{ fetchJob : "workflowEngineId"
    cable }o--o{ _cable : "cableId"
    duct }o--o{ _duct : "ductId"
    pole }o--o{ _pole : "poleId"
    document }o--o{ _cable : "documentId"
    document }o--o{ _site : "documentId"
    adminKafka }o--o{ alertPublish : "kafkaId"
    alert }o--o{ alertWorkflow : "alertId"
    ne }o--o{ _nePort : "neId"
    _ne }o--o{ _nePortCoax : "neTsId"
    document }o--o{ _trench : "documentId"
    cve }o--o{ cvePlatforms : "cveId"
    _ne }o--o{ _nePortVirtual : "neTsId"
    _ne }o--o{ _nePortEthernet : "neTsId"
    alert }o--o{ alertContent : "alertId"
    _ne }o--o{ _nePortLoopback : "neTsId"
    _rack }o--o{ _rackSlot : "rackTsId"
    service }o--o{ _serviceIngress : "serviceId"
    cve }o--o{ cveVersions : "cveId"
    cable }o--o{ _cableSingleFiber : "cableId"
    cable }o--o{ _cableCopper : "cableId"
    ne }o--o{ _serviceEgress : "neId"
    trench }o--o{ _trenchCoordinate : "trenchId"
    adminEmail }o--o{ adminEmailReceive : "adminEmailId"
    ne }o--o{ _ne : "neId"
    document }o--o{ _rack : "documentId"
    alertNotify }o--o{ alertQueue : "notifyAlertId"
    cable }o--o{ _cableEthernet : "cableId"
    rack }o--o{ _ne : "rackId"
    duct }o--o{ _duct : "within"
    site }o--o{ _ne : "siteId"
    adminKafka }o--o{ fetchJob : "kafkaId"
    site }o--o{ _site : "siteId"
    document }o--o{ _service : "documentId"
    fetchJob }o--o{ fetchQueue : "fetchJobId"
    alertNotify }o--o{ alertNotifyRecipient : "alertNotifyId"
    _ne }o--o{ _nePortXdsl : "neTsId"
    alertCallback }o--o{ alertQueue : "callbackAlertId"
    alert }o--o{ alertCallback : "alertId"
    rack }o--o{ _rack : "rackId"
    document }o--o{ _document : "documentId"
    _service }o--o{ _serviceIngress : "serviceTsId"
    ne }o--o{ fetchJob : "neId"
    document }o--o{ _duct : "documentId"
    service }o--o{ _service : "serviceId"
    alertWorkflow }o--o{ alertQueue : "workflowAlertId"
    adminWorkflow }o--o{ alertWorkflow : "workflowEngineId"
    alert }o--o{ alertNotify : "alertId"
    cable }o--o{ _cableMultiFiber : "cableId"
    _trench }o--o{ _trenchCoordinate : "trenchTsId"
    adminEmail }o--o{ fetchJob : "emailId"
    document }o--o{ _pole : "documentId"
    cable }o--o{ _cableCoax : "cableId"
    _ne }o--o{ _nePortFiber : "neTsId"
    alertPublish }o--o{ alertQueue : "publishAlertId"
    alert }o--o{ alertQueue : "alertId"
    site }o--o{ _rack : "siteId"
    adminEmail }o--o{ alertNotify : "emailProviderId"
    _ne }o--o{ _nePort : "neTsId"
    ne }o--o{ _serviceIngress : "neId"
    _service }o--o{ _serviceEgress : "serviceTsId"
    service }o--o{ _serviceEgress : "serviceId"
    adminEmail }o--o{ adminEmailSend : "adminEmailId"
    document }o--o{ _ne : "documentId"
    trench }o--o{ _duct : "trenchId"
    trench }o--o{ _trench : "trenchId"
