erDiagram
    alertQueue {integer qId timestamp point boolean delete enum alertType varchar alertId varchar callbackAlertId varchar publishAlertId varchar notifyAlertId varchar workflowAlertId}
    _document {integer tsId enum source timestamp point decimal probability varchar documentId enum mimeType varchar path varchar name integer sizeBytes varchar md5Hash}
    _nePort {integer tsId timestamp point enum source varchar neId integer neTsId varchar name enum technology enum state integer errorCount varchar macAddress}
    _nePortXdsl {integer tsId integer neTsId enum category integer rate enum unit}
    adminEmail {varchar id varchar vendor varchar address varchar name}
    costPole {enum purpose enum classifier decimal costPerUnit}
    cvePlatforms {integer id varchar cveId varchar platform}
    _ne {integer tsId timestamp point varchar neId enum source decimal probability enum country varchar reference varchar host varchar mgmtIP enum protocol integer port enum typeSecret varchar vendor varchar model varchar image varchar version timestamp commissioned timestamp decommissioned decimal cost boolean hasDocument varchar siteId varchar rackId varchar slotPosition varchar config varchar documentId}
    _nePortVirtual {integer tsId integer neTsId integer rate enum unit}
    correlate {varchar id varchar sourceObject varchar sourcereference varchar sourceValue varchar destinationObject varchar destinationreference varchar destinationValue enum type varchar fetchJobId}
    cve {varchar id timestamp published timestamp updated varchar vendor varchar uri}
    cveVersions {integer id varchar cveId varchar lessThan varchar status varchar version varchar versionType}
    _cable {integer tsId timestamp point enum source decimal probability varchar cableId varchar reference enum country varchar ductId varchar poleId enum technology decimal cost boolean hasDocument integer coaxTsId integer copperTsId integer ethernetTsId integer singleFiberTsId integer multiFiberTsId varchar documentId}
    _cableCoax {integer tsId timestamp point enum source varchar cableId decimal frequencyLow decimal frequencyHigh integer channels decimal width enum unit enum state}
    alertCallback {varchar id varchar alertId varchar requestorId varchar subscriptionId varchar callbackUrl enum authentication integer retries integer currentRetry integer retryDelay integer maxLifeRetries integer currentLifeRetries}
    costService {enum type integer rate enum unit integer lagMembers decimal costPerUnit}
    currency {varchar id varchar name enum symbol enum isoCode boolean systemDefault decimal rateFromDefault}
    alertContent {varchar id timestamp point varchar alertId varchar content}
    document {varchar id boolean delete timestamp tsPoint integer historicalTsId integer plannedTsId integer predictedTsId}
    duct {varchar id boolean delete timestamp tsPoint integer historicalTsId integer plannedTsId integer predictedTsId}
    _nePortFiber {integer tsId integer neTsId integer rate enum unit enum mode}
    _trench {integer tsId timestamp point varchar trenchId enum source decimal probability enum country boolean countryChecked varchar reference enum purpose decimal depth enum classifier enum unit enum type integer premisesPassed enum area decimal cost boolean hasDocument varchar jobId varchar permitId timestamp plannedStart timestamp plannedCompletion integer plannedDuration enum plannedUnit timestamp actualStart timestamp actualCompletion integer actualDuration enum actualUnit enum state varchar connectsToSiteId varchar connectsToTrenchId varchar connectsToPoleId varchar documentId varchar wkt decimal distanceTotal enum distanceUnit}
    alertPublish {varchar id varchar alertId varchar requestorId varchar publicationId varchar kafkaId varchar topic}
    replicationQueue {integer qId timestamp point boolean delete enum resource varchar id enum state}
    _cableEthernet {integer tsId timestamp point enum source varchar cableId enum category integer rate enum unit enum state}
    _rack {integer tsId timestamp point varchar rackId enum source decimal probability varchar reference enum country timestamp commissioned timestamp decommissioned varchar siteId integer floor varchar floorArea integer floorRow integer floorColumn decimal cost boolean hasDocument decimal X decimal Y decimal Z varchar M point_2d geoPoint decimal depth decimal height decimal width enum unit integer slots varchar documentId}
    alertWorkflow {varchar id varchar alertId varchar requestorId varchar workflowEngineId varchar workflowRunnerId varchar flowName}
    costCable {enum technology enum unit decimal costPerUnit}
    rack {varchar id boolean delete timestamp tsPoint integer historicalTsId integer plannedTsId integer predictedTsId}
    trench {varchar id boolean delete timestamp tsPoint integer historicalTsId integer plannedTsId integer predictedTsId}
    _duct {integer tsId timestamp point varchar ductId varchar trenchId enum source decimal probability enum country varchar reference enum purpose enum category decimal cost boolean hasDocument integer configuration enum state varchar within decimal placementVertical decimal placementHorizontal enum placementUnit varchar documentId}
    adminKafka {varchar id varchar name varchar clientId varchar host integer port integer retryDelay integer retries enum acks integer linger integer batchSize integer bufferMemory integer maxInFlightRequestsPerConnection enum compressionMethod enum authentication}
    alertNotifyRecipient {varchar id varchar alertNotifyId varchar notificationId varchar recipient}
    predictQueue {integer qId timestamp point boolean delete enum resource varchar id enum state}
    service {varchar id boolean delete timestamp tsPoint integer historicalTsId integer plannedTsId integer predictedTsId}
    worldGeo {enum country geometry geoCollection}
    _cableFiberState {integer tsId timestamp point enum source integer fiberTsId varchar cableId integer ribbon integer strand enum state}
    adminEmailReceive {varchar id varchar adminEmailId varchar host integer port enum protocol boolean encryptionEnabled boolean encryptionStartTls varchar rootFolder enum folderSeparator}
    adminMap {varchar id enum vendor boolean systemDefault varchar renderUrl enum typeSecret}
    alert {varchar id boolean delete varchar description varchar cronTime varchar function boolean enabled}
    costDuct {enum category integer configuration enum unit decimal costPerUnit}
    costRack {integer slots decimal costPerUnit}
    fetchQueue {integer qId timestamp point boolean delete varchar fetchJobId}
    ne {varchar id boolean delete timestamp tsPoint integer historicalTsId integer plannedTsId integer predictedTsId}
    secret {varchar scope varchar realm enum type timestamp expiration varchar identityProviderBase varchar identityProviderAuthorization varchar identityProviderToken varchar identityProviderWellKnown varchar plainUsername varchar plainPassword varchar sshUsername varchar sshKeyPassphrase varchar sshKeyPublic varchar sshKeyPrivate varchar sshHostCA varchar sslPrivate varchar sslCA enum snmpVersion varchar snmpCommunityRead varchar snmpCommunityWrite varchar snmpCommunityTrap varchar snmpUsername enum snmpAuthorizationProtocol varchar snmpAuthorizationPassword enum snmpEncryptionProtocol varchar snmpEncryptionPassword varchar tokenIdentity varchar tokenKey}
    _serviceEgress {integer tsId timestamp point enum source varchar serviceId integer serviceTsId varchar neId varchar nePort integer cVlanId integer sVlanId integer lagMember}
    alertNotify {varchar id varchar alertId varchar requestorId varchar emailProviderId varchar notificationId varchar subject}
    costTrench {enum purpose enum type enum unit decimal costPerUnit}
    pole {varchar id boolean delete timestamp tsPoint integer historicalTsId integer plannedTsId integer predictedTsId}
    _service {integer tsId timestamp point varchar serviceId enum source decimal probability varchar reference enum country varchar customerName varchar customerReference timestamp commissioned timestamp decommissioned enum type decimal cost boolean hasDocument integer rate enum unit varchar lagGroup integer lagMembers varchar documentId}
    _site {integer tsId timestamp point varchar siteId enum source decimal probability varchar reference timestamp commissioned timestamp decommissioned enum area enum type boolean onNet decimal cost boolean hasDocument enum country boolean countryChecked varchar region varchar town varchar district varchar street varchar premisesNameNumber varchar postalCode decimal X decimal Y decimal Z varchar M varchar documentId varchar wkt point_2d geoPoint}
    adminWorkflow {varchar id varchar name varchar engineUrl enum engineType}
    costSite {enum area enum type decimal costPerUnit}
    site {varchar id boolean delete timestamp tsPoint integer historicalTsId integer plannedTsId integer predictedTsId}
    _cableMultiFiber {integer tsId timestamp point enum source varchar cableId integer ribbons integer strands enum mode integer channels integer width integer rate enum unit}
    _nePortCoax {integer tsId integer neTsId decimal frequencyLow decimal frequencyHigh integer channels decimal width enum unit}
    _nePortEthernet {integer tsId integer neTsId enum category integer rate enum unit}
    _trenchCoordinate {integer tsId timestamp point integer trenchTsId varchar trenchId enum source decimal X decimal Y decimal Z varchar M point_2d geoPoint}
    fetchJob {varchar id varchar description enum protocol varchar cronTime boolean enabled varchar neId varchar emailId varchar emailAddress varchar emailSubject varchar fileUrl varchar httpUrl varchar kafkaId varchar kafkaTopic varchar mysqlHost varchar mysqlDatabase varchar mysqlSchema integer mysqlPort varchar oracleHost varchar oracleProtocol varchar oracleSid integer oraclePort varchar oracleSchema varchar snmpReadOid varchar snmpMibDocumentId varchar workflowEngineId varchar workflowRunnerId varchar workflowName integer retries integer currentRetry integer retryDelay integer maxLifeRetries integer currentLifeRetries varchar function}
    _cableSingleFiber {integer tsId timestamp point enum source varchar cableId integer strands enum mode integer channels integer width integer rate enum unit}
    _siteHvac {integer tsId timestamp point varchar siteId integer siteTsId enum source decimal probability boolean occupied enum unit enum operation decimal internalTemperature decimal setPointTemperature decimal externalTemperature decimal internalHumidity decimal externalHumidity decimal stpEnergyEfficiency decimal stpThermalOptimumEnergy decimal stpThermalMinimumComfort decimal stpThermalRecommendedComfort}
    adminData {varchar id integer historicalDuration enum historicalUnit integer predictedDuration enum predictedUnit}
    costNe {varchar vendor varchar model decimal costPerUnit}
    _nePortLoopback {integer tsId integer neTsId integer rate enum unit}
    _pole {integer tsId timestamp point varchar poleId enum source decimal probability enum country boolean countryChecked varchar reference enum purpose decimal height enum classifier enum unit integer premisesPassed enum area decimal cost boolean hasDocument varchar jobId varchar permitId timestamp plannedStart timestamp plannedCompletion integer plannedDuration enum plannedUnit timestamp actualStart timestamp actualCompletion integer actualDuration enum actualUnit enum state varchar connectsToSiteId varchar connectsToTrenchId varchar connectsToPoleId decimal X decimal Y decimal Z varchar M varchar documentId point_2d geoPoint}
    adminEmailSend {varchar id varchar adminEmailId varchar host integer port enum protocol enum authentication boolean encryptionEnabled boolean encryptionStartTls}
    cable {varchar id boolean delete timestamp tsPoint integer historicalTsId integer plannedTsId integer predictedTsId}
    _cableCopper {integer tsId timestamp point enum source varchar cableId integer twistedPairs enum state}
    _rackSlot {integer tsId timestamp point enum source decimal probability varchar rackId integer rackTsId integer slot enum usage varchar neId varchar host}
    _serviceIngress {integer tsId timestamp point enum source varchar serviceId integer serviceTsId varchar neId varchar nePort integer cVlanId integer sVlanId integer lagMember}
    alertPublish }o--o{ alertQueue : "publishAlertId"
    rack }o--o{ _rackSlot : "rackId"
    document }o--o{ fetchJob : "snmpMibDocumentId"
    document }o--o{ _cable : "documentId"
    adminEmail }o--o{ alertNotify : "emailProviderId"
    document }o--o{ _trench : "documentId"
    trench }o--o{ _trenchCoordinate : "trenchId"
    cable }o--o{ _cable : "cableId"
    site }o--o{ _rack : "siteId"
    adminKafka }o--o{ fetchJob : "kafkaId"
    rack }o--o{ _rack : "rackId"
    adminEmail }o--o{ fetchJob : "emailId"
    document }o--o{ _pole : "documentId"
    document }o--o{ _ne : "documentId"
    cve }o--o{ cvePlatforms : "cveId"
    cable }o--o{ _cableMultiFiber : "cableId"
    ne }o--o{ _ne : "neId"
    ne }o--o{ fetchJob : "neId"
    pole }o--o{ _pole : "poleId"
    document }o--o{ _service : "documentId"
    alertNotify }o--o{ alertQueue : "notifyAlertId"
    alertNotify }o--o{ alertNotifyRecipient : "alertNotifyId"
    site }o--o{ _site : "siteId"
    cable }o--o{ _cableCopper : "cableId"
    ne }o--o{ _serviceEgress : "neId"
    ne }o--o{ _serviceIngress : "neId"
    alert }o--o{ alertQueue : "alertId"
    document }o--o{ _document : "documentId"
    _site }o--o{ _siteHvac : "siteTsId"
    fetchJob }o--o{ correlate : "fetchJobId"
    alert }o--o{ alertNotify : "alertId"
    alert }o--o{ alertCallback : "alertId"
    site }o--o{ _siteHvac : "siteId"
    document }o--o{ _duct : "documentId"
    fetchJob }o--o{ fetchQueue : "fetchJobId"
    duct }o--o{ _duct : "within"
    ne }o--o{ _nePort : "neId"
    adminEmail }o--o{ adminEmailSend : "adminEmailId"
    adminEmail }o--o{ adminEmailReceive : "adminEmailId"
    service }o--o{ _service : "serviceId"
    alertWorkflow }o--o{ alertQueue : "workflowAlertId"
    document }o--o{ _site : "documentId"
    alert }o--o{ alertWorkflow : "alertId"
    cable }o--o{ _cableFiberState : "cableId"
    service }o--o{ _serviceEgress : "serviceId"
    site }o--o{ _ne : "siteId"
    duct }o--o{ _duct : "ductId"
    document }o--o{ _rack : "documentId"
    service }o--o{ _serviceIngress : "serviceId"
    trench }o--o{ _duct : "trenchId"
    adminKafka }o--o{ alertPublish : "kafkaId"
    adminWorkflow }o--o{ fetchJob : "workflowEngineId"
    trench }o--o{ _trench : "trenchId"
    alert }o--o{ alertContent : "alertId"
    alertCallback }o--o{ alertQueue : "callbackAlertId"
    cable }o--o{ _cableEthernet : "cableId"
    cable }o--o{ _cableSingleFiber : "cableId"
    adminWorkflow }o--o{ alertWorkflow : "workflowEngineId"
    rack }o--o{ _ne : "rackId"
    alert }o--o{ alertPublish : "alertId"
    cve }o--o{ cveVersions : "cveId"
    cable }o--o{ _cableCoax : "cableId"
